replicaCount: 1

image:
  repository: orders-service
  tag: latest

service:
  type: ClusterIP
  port: 8082

secrets:
  dbPassword: ""
  dbName: "order_db"

resources:
  requests:
    cpu: "10m"      
    memory: "32Mi"   
  limits:
    cpu: "100m"
    memory: "128Mi"
