global:
  repository: 723580626973.dkr.ecr.us-east-1.amazonaws.com
  tag: latest
  awsRegion: "us-east-1"
  secrets:
    authDbPassword: ""
    orderDbPassword: ""
    jwtSecret: ""
    stripeApiKey: ""
  database:
    host: "ecommercemain.c6nao6eycmq2.us-east-1.rds.amazonaws.com"
    port: 5432
  sharedEnv:
    LOG_LEVEL: "info"
    AUTH_API_URL: "http://auth-service:8080"
    CART_API_URL: "http://cart-service:8081"
    NOTIFICATION_API_URL: "http://notification-service:8082"
    ORDER_API_URL: "http://order-service:8083"
    PAYMENT_API_URL: "http://payment-service:8084"
    PRODUCT_API_URL: "http://product-service:8085"
  image:
    tag: 7dd9f9e309b04c6d6f051375e5a74237948348f5
frontend:
  replicaCount: 1
  image:
    repository: "frontend-service"
  service:
    port: 80
auth:
  replicaCount: 1
  image:
    repository: "auth-service"
  service:
    type: ClusterIP
    port: 8080
  secrets:
    dbName: "auth_db" # Unique DB name on shared RDS
    jwtSecret: "a-long-random-32-character-string"
cart:
  replicaCount: 1
  image:
    repository: "cart-service"
  service:
    port: 8081
  secrets:
    dbName: "cart_db"
notification:
  replicaCount: 1
  image:
    repository: "notification-service"
  service:
    port: 8082
order:
  replicaCount: 1
  image:
    repository: "orders-service"
  service:
    port: 8083
  secrets:
    dbName: "order_db"
payment:
  replicaCount: 1
  image:
    repository: "payment-service"
  service:
    port: 8084
product:
  replicaCount: 1
  image:
    repository: "product-service"
  service:
    port: 8085
