grafana:
  enabled: true
  adminPassword: "admin" 
  
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: grafana.baashe.uk
    hosts:
      - grafana.baashe.uk
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.baashe.uk

  persistence:
    enabled: false

prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: prometheus.baashe.uk
    hosts:
      - prometheus.baashe.uk
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.baashe.uk

  prometheusSpec:
    retention: 1d # Lowered retention for memory savings
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
        cpu: "300m"
    
    storageSpec:
      emptyDir:
        medium: Memory